### ISSUE TITLE
Paging占位符，空指针报错

### ISSUE THREAD

**Issue by wjlight** [cat-x/MultiTypeRecyclerView#1]
我使用了paging的占位符，然后报了空指针错误

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at xyz.a1api.multirecycler.BaseMultiAdapter.indexInTypesOf(BaseMultiAdapter.java:2200)
        at xyz.a1api.paging.PagedMultiAdapter.getDefItemViewType(PagedMultiAdapter.java:85)
        at xyz.a1api.multirecycler.BaseMultiAdapter.getItemViewType(BaseMultiAdapter.java:769)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6186)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)

**Comment by cat-x** [comment]
Android的新组件目前没有精力来进行兼容。
建议可以参考com.github.CymChad:BaseRecyclerViewAdapterHelper
